version: "3.9"
services:
  web:
    build:
      context: .
      args:
        DOCKER_UID: 1000
        DOCKER_GID: 1000
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/home/app/myapp
      - web-node-modules:/home/app/myapp/node_modules
    ports:
      - 3000:3000

volumes:
  web-node-modules: